---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
   - 84.38.64.209 
  #loadBalancerIP: 84.38.64.209 
  ports:
   - port: 80
     targetPort: 8080
  selector:
    service: ambassador
