---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: grafana-ambassador-mapping
spec:
  prefix: /
  service: isitio-system.grafana:3000
  host: grafana.redwire.consulting
  timeout_ms: 10000
  idle_timeout_ms: 500000
  connect_timeout_ms: 4000