---
resources:
  - rbac.yaml
  - configmap.yaml
  - pvc.yaml
  - redis.yaml
  - front.yaml
  - webmail.yaml
  - imap.yaml
  - security.yaml
  - smtp.yaml
  - fetchmail.yaml
  - admin.yaml
  - webdav.yaml
  - admin-ingress.yaml
  - webdav-ingress.yaml
  - security-ingress.yaml
  - webmail-ingress.yaml
