---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterblock-hdd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: glusterblock-hdd
  local:
    path: /mnt/k8s/glusterblock-hdd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vserver1207
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-heketi-hdd
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gluster-heketi-hdd
  local:
    path: /mnt/k8s/gluster-heketi-hdd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - vserver1207
