---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: wp-mapping
      prefix: /
      service: wordpress:80
      host: lesetraum.blog
      timeout_ms: 10000
      idle_timeout_ms: 500000
      connect_timeout_ms: 4000
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: wp-www-mapping
      prefix: /
      service: lesetraum.blog
      host: www.lesetraum.blog
      timeout_ms: 10000
      idle_timeout_ms: 500000
      connect_timeout_ms: 4000
      host_redirect: true
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: ClusterIP
