---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lesetraum-site-certs
  namespace: default
spec:
  secretName: lesetraum-site-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - lesetraum.blog
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - lesetraum.blog
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lesetraum-www-certs
  namespace: default
spec:
  secretName: lesetraum-www-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - www.lesetraum.blog
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.lesetraum.blog
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lesetraum-mail-certs
  namespace: default
spec:
  secretName: lesetraum-mail-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - mail.lesetraum.blog
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - mail.lesetraum.blog